# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-05-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
