# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-05-13 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0016_auto_20230513_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='accreditated',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='assessment_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='duration',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='estimation_tools',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='hours',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='hours_per_week',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='proctoring_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='proctoring_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='requirements',
            field=models.TextField(null=True),
        ),
    ]
