# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-05-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0017_auto_20230513_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='business_version',
            field=models.IntegerField(default=b'7'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='duration',
            field=models.IntegerField(default=b'7'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='hours',
            field=models.IntegerField(default=b'40'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='hours_per_week',
            field=models.IntegerField(default=b'7'),
        ),
    ]
