# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-05-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0018_auto_20230515_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='accreditated',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='assessment_description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='business_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='competences',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='estimation_tools',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='hours',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='hours_per_week',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='proctoring_service',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='proctoring_type',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='requirements',
            field=models.TextField(default=b''),
        ),
    ]
