# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-29 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_creators', '0002_auto_20200821_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreator',
            name='note',
            field=models.CharField(blank=True, help_text='Optional notes about this user (for example, why course creation access was denied)', max_length=512),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='state',
            field=models.CharField(choices=[(b'unrequested', 'unrequested'), (b'pending', 'pending'), (b'granted', 'granted'), (b'denied', 'denied')], default=b'unrequested', help_text='Current course creator state', max_length=24),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='state_changed',
            field=models.DateTimeField(auto_now_add=True, help_text='The date when state was last updated', verbose_name=b'state last updated'),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='user',
            field=models.OneToOneField(help_text='Studio user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
