# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-12-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200902_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='mode',
            field=models.CharField(default=b'verified', max_length=100),
        ),
    ]
